---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[test::prepare]
      - recipe[nomad::default]
      - recipe[test::exercise]
    attributes:
      nomad:
        server_enabled: true
        bootstrap_expect: 1
